name: CI



on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.2
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-file: development
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
      - name: Check 100% code coverage
        shell: php {0}
        run: |
          <?php
          $metrics = simplexml_load_file('clover.xml')->project->metrics;
          exit((int) $metrics['statements'] === (int) $metrics['coveredstatements'] ? 0 : 1);